// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    cluster_id,
    node_id,
    started_at,
    status,
    tag
) VALUES (
    $1,
    $2,
    COALESCE($3, NOW()),
    COALESCE($4, 'running'),
    $5
)
RETURNING id, cluster_id, node_id, started_at, finished_at, duration_hours, status, tag
`

type CreateJobParams struct {
	ClusterID string  `json:"cluster_id"`
	NodeID    int64   `json:"node_id"`
	Column3   any     `json:"column_3"`
	Column4   any     `json:"column_4"`
	Tag       *string `json:"tag"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ClusterID,
		arg.NodeID,
		arg.Column3,
		arg.Column4,
		arg.Tag,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationHours,
		&i.Status,
		&i.Tag,
	)
	return i, err
}

const getJobByClusterAndJobID = `-- name: GetJobByClusterAndJobID :one
SELECT id, cluster_id, node_id, started_at, finished_at, duration_hours, status, tag FROM jobs
WHERE cluster_id = $1 AND id = $2 LIMIT 1
`

type GetJobByClusterAndJobIDParams struct {
	ClusterID string `json:"cluster_id"`
	ID        int64  `json:"id"`
}

func (q *Queries) GetJobByClusterAndJobID(ctx context.Context, arg GetJobByClusterAndJobIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByClusterAndJobID, arg.ClusterID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationHours,
		&i.Status,
		&i.Tag,
	)
	return i, err
}

const listJobsByCluster = `-- name: ListJobsByCluster :many
SELECT id, cluster_id, node_id, started_at, finished_at, duration_hours, status, tag FROM jobs
WHERE cluster_id = $1
ORDER BY started_at DESC, id DESC
`

func (q *Queries) ListJobsByCluster(ctx context.Context, clusterID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationHours,
			&i.Status,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByNode = `-- name: ListJobsByNode :many
SELECT id, cluster_id, node_id, started_at, finished_at, duration_hours, status, tag FROM jobs
WHERE node_id = $1
ORDER BY started_at DESC, id DESC
`

func (q *Queries) ListJobsByNode(ctx context.Context, nodeID int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationHours,
			&i.Status,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET started_at  = COALESCE($2, started_at),
    finished_at = COALESCE($3, finished_at),
    status      = COALESCE($4, status),
    tag         = COALESCE($5, tag),
    duration_hours = COALESCE($6, duration_hours)
WHERE id = $1
RETURNING id, cluster_id, node_id, started_at, finished_at, duration_hours, status, tag
`

type UpdateJobParams struct {
	ID            int64              `json:"id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Status        string             `json:"status"`
	Tag           *string            `json:"tag"`
	DurationHours pgtype.Interval    `json:"duration_hours"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.Tag,
		arg.DurationHours,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationHours,
		&i.Status,
		&i.Tag,
	)
	return i, err
}
