// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  cluster_id, node_id
) VALUES (
  $1, $2
)
RETURNING id, cluster_id, node_id, started_at, finished_at, status
`

type CreateJobParams struct {
	ClusterID string `json:"cluster_id"`
	NodeID    int64  `json:"node_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ClusterID, arg.NodeID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const deleteJobsByCluster = `-- name: DeleteJobsByCluster :exec
DELETE FROM jobs
WHERE cluster_id = $1
`

func (q *Queries) DeleteJobsByCluster(ctx context.Context, clusterID string) error {
	_, err := q.db.Exec(ctx, deleteJobsByCluster, clusterID)
	return err
}

const deleteJobsByNode = `-- name: DeleteJobsByNode :exec
DELETE FROM jobs
WHERE node_id = $1
`

func (q *Queries) DeleteJobsByNode(ctx context.Context, nodeID int64) error {
	_, err := q.db.Exec(ctx, deleteJobsByNode, nodeID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, cluster_id, node_id, started_at, finished_at, status FROM jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
	)
	return i, err
}

const getJobByClusterAndJobId = `-- name: GetJobByClusterAndJobId :one
SELECT id, cluster_id, node_id, started_at, finished_at, status FROM jobs
WHERE cluster_id = $1 AND id = $2 LIMIT 1
`

type GetJobByClusterAndJobIdParams struct {
	ClusterID string `json:"cluster_id"`
	ID        int64  `json:"id"`
}

func (q *Queries) GetJobByClusterAndJobId(ctx context.Context, arg GetJobByClusterAndJobIdParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByClusterAndJobId, arg.ClusterID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, cluster_id, node_id, started_at, finished_at, status FROM jobs
ORDER BY started_at DESC, id DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByCluster = `-- name: ListJobsByCluster :many
SELECT id, cluster_id, node_id, started_at, finished_at, status FROM jobs
WHERE cluster_id = $1
ORDER BY started_at DESC, id DESC
`

func (q *Queries) ListJobsByCluster(ctx context.Context, clusterID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByNode = `-- name: ListJobsByNode :many
SELECT id, cluster_id, node_id, started_at, finished_at, status FROM jobs
WHERE node_id = $1
ORDER BY started_at DESC, id DESC
`

func (q *Queries) ListJobsByNode(ctx context.Context, nodeID int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET started_at = COALESCE($2, started_at),
    finished_at = COALESCE($3, finished_at),
    status = COALESCE($4, status)
WHERE id = $1
RETURNING id, cluster_id, node_id, started_at, finished_at, status
`

type UpdateJobParams struct {
	ID         int64              `json:"id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Status     string             `json:"status"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
	)
	return i, err
}
