// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at
`

type CreateJobParams struct {
	NodeID        int64            `json:"node_id"`
	ClusterID     string           `json:"cluster_id"`
	JobNumber     int32            `json:"job_number"`
	Tag           *string          `json:"tag"`
	User          *string          `json:"user"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	FinishedAt    pgtype.Timestamp `json:"finished_at"`
	DurationHours pgtype.Numeric   `json:"duration_hours"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.NodeID,
		arg.ClusterID,
		arg.JobNumber,
		arg.Tag,
		arg.User,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationHours,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ClusterID,
		&i.JobNumber,
		&i.Tag,
		&i.User,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationHours,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const deleteJobsByCluster = `-- name: DeleteJobsByCluster :exec
DELETE FROM jobs
WHERE cluster_id = $1
`

func (q *Queries) DeleteJobsByCluster(ctx context.Context, clusterID string) error {
	_, err := q.db.Exec(ctx, deleteJobsByCluster, clusterID)
	return err
}

const deleteJobsByNode = `-- name: DeleteJobsByNode :exec
DELETE FROM jobs
WHERE node_id = $1
`

func (q *Queries) DeleteJobsByNode(ctx context.Context, nodeID int64) error {
	_, err := q.db.Exec(ctx, deleteJobsByNode, nodeID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at FROM jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ClusterID,
		&i.JobNumber,
		&i.Tag,
		&i.User,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationHours,
		&i.CreatedAt,
	)
	return i, err
}

const getJobByClusterAndJobId = `-- name: GetJobByClusterAndJobId :one
SELECT id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at FROM jobs
WHERE cluster_id = $1 AND job_number = $2 LIMIT 1
`

type GetJobByClusterAndJobIdParams struct {
	ClusterID string `json:"cluster_id"`
	JobNumber int32  `json:"job_number"`
}

func (q *Queries) GetJobByClusterAndJobId(ctx context.Context, arg GetJobByClusterAndJobIdParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByClusterAndJobId, arg.ClusterID, arg.JobNumber)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ClusterID,
		&i.JobNumber,
		&i.Tag,
		&i.User,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationHours,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ClusterID,
			&i.JobNumber,
			&i.Tag,
			&i.User,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByCluster = `-- name: ListJobsByCluster :many
SELECT id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at FROM jobs
WHERE cluster_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListJobsByCluster(ctx context.Context, clusterID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ClusterID,
			&i.JobNumber,
			&i.Tag,
			&i.User,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByNode = `-- name: ListJobsByNode :many
SELECT id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at FROM jobs
WHERE node_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListJobsByNode(ctx context.Context, nodeID int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ClusterID,
			&i.JobNumber,
			&i.Tag,
			&i.User,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at FROM jobs
WHERE "user" = $1
ORDER BY started_at DESC
`

func (q *Queries) ListJobsByUser(ctx context.Context, user *string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByUser, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ClusterID,
			&i.JobNumber,
			&i.Tag,
			&i.User,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET tag = $2,
    "user" = $3,
    started_at = $4,
    finished_at = $5,
    duration_hours = $6
WHERE id = $1
RETURNING id, node_id, cluster_id, job_number, tag, "user", started_at, finished_at, duration_hours, created_at
`

type UpdateJobParams struct {
	ID            int64            `json:"id"`
	Tag           *string          `json:"tag"`
	User          *string          `json:"user"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	FinishedAt    pgtype.Timestamp `json:"finished_at"`
	DurationHours pgtype.Numeric   `json:"duration_hours"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Tag,
		arg.User,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationHours,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ClusterID,
		&i.JobNumber,
		&i.Tag,
		&i.User,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationHours,
		&i.CreatedAt,
	)
	return i, err
}
