// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cluster struct {
	ID           string           `json:"id"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Job struct {
	ID            int64            `json:"id"`
	NodeID        int64            `json:"node_id"`
	ClusterID     string           `json:"cluster_id"`
	JobNumber     int32            `json:"job_number"`
	Tag           *string          `json:"tag"`
	User          *string          `json:"user"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	FinishedAt    pgtype.Timestamp `json:"finished_at"`
	DurationHours pgtype.Numeric   `json:"duration_hours"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Node struct {
	ID               int64            `json:"id"`
	ClusterID        string           `json:"cluster_id"`
	NodeName         string           `json:"node_name"`
	CurrentJobNumber *int32           `json:"current_job_number"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}
