// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cluster struct {
	ID           string             `json:"id"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID         int64              `json:"id"`
	ClusterID  string             `json:"cluster_id"`
	NodeID     int64              `json:"node_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Status     string             `json:"status"`
}

type Node struct {
	ID                int64              `json:"id"`
	ClusterID         string             `json:"cluster_id"`
	NodeName          string             `json:"node_name"`
	WebhookSecretHash string             `json:"webhook_secret_hash"`
	CurrentJobID      *int64             `json:"current_job_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
