// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package repo

import (
	"context"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
  cluster_id, node_name, current_job_number
) VALUES (
  $1, $2, $3
)
RETURNING id, cluster_id, node_name, current_job_number, created_at
`

type CreateNodeParams struct {
	ClusterID        string `json:"cluster_id"`
	NodeName         string `json:"node_name"`
	CurrentJobNumber *int32 `json:"current_job_number"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode, arg.ClusterID, arg.NodeName, arg.CurrentJobNumber)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeName,
		&i.CurrentJobNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes
WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const deleteNodesByCluster = `-- name: DeleteNodesByCluster :exec
DELETE FROM nodes
WHERE cluster_id = $1
`

func (q *Queries) DeleteNodesByCluster(ctx context.Context, clusterID string) error {
	_, err := q.db.Exec(ctx, deleteNodesByCluster, clusterID)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, cluster_id, node_name, current_job_number, created_at FROM nodes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeName,
		&i.CurrentJobNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeByClusterAndNodeId = `-- name: GetNodeByClusterAndNodeId :one
SELECT id, cluster_id, node_name, current_job_number, created_at FROM nodes
WHERE cluster_id = $1 AND node_name = $2 LIMIT 1
`

type GetNodeByClusterAndNodeIdParams struct {
	ClusterID string `json:"cluster_id"`
	NodeName  string `json:"node_name"`
}

func (q *Queries) GetNodeByClusterAndNodeId(ctx context.Context, arg GetNodeByClusterAndNodeIdParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByClusterAndNodeId, arg.ClusterID, arg.NodeName)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeName,
		&i.CurrentJobNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, cluster_id, node_name, current_job_number, created_at FROM nodes
ORDER BY created_at DESC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeName,
			&i.CurrentJobNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByCluster = `-- name: ListNodesByCluster :many
SELECT id, cluster_id, node_name, current_job_number, created_at FROM nodes
WHERE cluster_id = $1
ORDER BY node_name ASC
`

func (q *Queries) ListNodesByCluster(ctx context.Context, clusterID string) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeName,
			&i.CurrentJobNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeJobNumber = `-- name: UpdateNodeJobNumber :one
UPDATE nodes
SET current_job_number = $2
WHERE id = $1
RETURNING id, cluster_id, node_name, current_job_number, created_at
`

type UpdateNodeJobNumberParams struct {
	ID               int64  `json:"id"`
	CurrentJobNumber *int32 `json:"current_job_number"`
}

func (q *Queries) UpdateNodeJobNumber(ctx context.Context, arg UpdateNodeJobNumberParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeJobNumber, arg.ID, arg.CurrentJobNumber)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeName,
		&i.CurrentJobNumber,
		&i.CreatedAt,
	)
	return i, err
}
