// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	DeleteCluster(ctx context.Context, id string) error
	GetCluster(ctx context.Context, id string) (Cluster, error)
	GetJobByClusterAndJobId(ctx context.Context, arg GetJobByClusterAndJobIdParams) (Job, error)
	GetNodeByWebhookSecretHash(ctx context.Context, webhookSecretHash string) (Node, error)
	ListJobsByCluster(ctx context.Context, clusterID string) ([]Job, error)
	ListJobsByNode(ctx context.Context, nodeID int64) ([]Job, error)
	ListNodesByCluster(ctx context.Context, clusterID string) ([]Node, error)
	UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateNodeCurrentJob(ctx context.Context, arg UpdateNodeCurrentJobParams) (Node, error)
}

var _ Querier = (*Queries)(nil)
